### ISSUE TITLE
SEA Conference Changes

### ISSUE THREAD

**Issue by djgagne** [djgagne/ams-ml-python-course#14]
I would like to make the following changes to the short course before the SEA Conference:

### Overall
* Add an interactive example for each module. 
* Move low-level code out of notebooks to the library.

### Module 1 (DJ):
* Fix PCA example and add visualization of PCA. 

### Module 2 (Ryan):
* Move some of the material, especially training/test set split to module 1.
* DJ will take the pre-processing items out of module 2 and then Ryan will finish other edits.

### Module 3 (DJ):
Add headings. 
Do actual backwards optimization on 32 subplot image.
Potentially switch out the ridge and lasso plot with https://stats.stackexchange.com/questions/341816/why-the-contour-of-lasso-and-ridge-regression-are-drawn-only-at-that-position-an.

### Module 4 (Ryan):
Remove pre-processing and training. 
Redo ordering:
1. Permutation Variable Importance
2. Saliency
3. Grad-CAM
4. Backwards Optimization
Bonus: Novelty Detection.

## Ryan's Notes
Will be 6 hours (0900-1600 with one-hour lunch break).
We plan to cover the same topics roughly.
Just Ryan and DJ teaching.

I will put in Grad-CAM before novelty detection and leave novelty detection as a bonus topic.
Replace “Citation” with actual title of my notebook.
Remove the long list of “pip install”.
Put constants in dictionary?
Don’t cover plotting and norm/denorm.
I should just have one block that loads all the data, normalizes, and binarizes.
I also will focus less on CNN setup.
Do motivation for interpretation at the beginning.
I can probably include more details on evaluation.
Olah figure with all the different chunking options might be confusing, since we use only output neuron.
DJ has a flow chart that explains BWO (I will use this).
Put saliency before BWO.
Order: saliency, Grad-CAM, BWO, novelty detection.

**Comment by thunderhoser** [comment]
Bullet points in green are done; those in red, I'm still working on.

```diff
- I will put in Grad-CAM before novelty detection and leave novelty detection as a bonus topic.
+ Replace “Citation” with actual title of my notebook.
+ Remove the long list of “pip install”.
- Put constants in dictionary?
+ Don’t cover plotting and norm/denorm.
- I should just have one block that loads all the data, normalizes, and binarizes.
+ I also will focus less on CNN setup.
- Do motivation for interpretation at the beginning.
- I can probably include more details on evaluation.
- Get rid of Olah figure with different neuron-grouping options.
- DJ has a flow chart that explains BWO (I will use this).
- Order: saliency, Grad-CAM, BWO, novelty detection.
```

**Comment by thunderhoser** [comment]
```diff
- I will put in Grad-CAM before novelty detection and leave novelty detection as a bonus topic.
+ Replace “Citation” with actual title of my notebook.
+ Remove the long list of “pip install”.
+ Remove constants from notebook.
+ Don’t cover plotting and norm/denorm.
+ I should just have one block that loads all the data, normalizes, and binarizes.
+ I also will focus less on CNN setup.
+ Do motivation for interpretation at the beginning.
+ Include more details on evaluation.
- Get rid of Olah figure with different neuron-grouping options.
- DJ has a flow chart that explains BWO (I will use this).
- Order: saliency, Grad-CAM, BWO, novelty detection.
```

**Comment by thunderhoser** [comment]
I still have the following to-do list:

- Insert DJ's flow chart for backwards optimization (haven't seen this yet).
- Edit Module 2 (waiting for you to remove stuff into Module 1).

Also, I decided to use the Olah figure with neuron-grouping options, but only once -- and I think I did a better job explaining this time.  All my changes are in ryan_branch right now.

**Comment by djgagne** [comment]
I just added my changes to module 1 and module 3 and will be merging shortly.
